/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewEntries;

import Admin.Admin;
import Classes.MyConnection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aby Balu
 */
public class AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form AddAdmin
     */
    public AddAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAddress_textArea_ = new javax.swing.JTextArea();
        txt_password = new javax.swing.JPasswordField();
        txt_password1 = new javax.swing.JPasswordField();
        mName_textField_ = new javax.swing.JTextField();
        lName_textField_ = new javax.swing.JTextField();
        userName_textField_ = new javax.swing.JTextField();
        jEmail_textField_ = new javax.swing.JTextField();
        jDOB_textField_ = new javax.swing.JTextField();
        bloodGroup_textField_ = new javax.swing.JTextField();
        phoneNo_textField_ = new javax.swing.JTextField();
        fName_textField_ = new javax.swing.JTextField();
        jButton_Clear_ = new javax.swing.JButton();
        jButton_Register_ = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jBack_Button_ = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jAddress_textArea_.setBackground(new java.awt.Color(108, 122, 137));
        jAddress_textArea_.setColumns(20);
        jAddress_textArea_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jAddress_textArea_.setForeground(new java.awt.Color(228, 241, 254));
        jAddress_textArea_.setLineWrap(true);
        jAddress_textArea_.setRows(5);
        jScrollPane1.setViewportView(jAddress_textArea_);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(630, 260, 130, 90);

        txt_password.setBackground(new java.awt.Color(108, 122, 137));
        txt_password.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(txt_password);
        txt_password.setBounds(360, 370, 130, 30);

        txt_password1.setBackground(new java.awt.Color(108, 122, 137));
        txt_password1.setForeground(new java.awt.Color(228, 241, 254));
        jPanel1.add(txt_password1);
        txt_password1.setBounds(360, 330, 130, 30);

        mName_textField_.setBackground(new java.awt.Color(108, 122, 137));
        mName_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        mName_textField_.setForeground(new java.awt.Color(228, 241, 254));
        mName_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mName_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(mName_textField_);
        mName_textField_.setBounds(360, 170, 130, 30);

        lName_textField_.setBackground(new java.awt.Color(108, 122, 137));
        lName_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lName_textField_.setForeground(new java.awt.Color(228, 241, 254));
        lName_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lName_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(lName_textField_);
        lName_textField_.setBounds(360, 210, 130, 30);

        userName_textField_.setBackground(new java.awt.Color(108, 122, 137));
        userName_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        userName_textField_.setForeground(new java.awt.Color(228, 241, 254));
        userName_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userName_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(userName_textField_);
        userName_textField_.setBounds(360, 250, 130, 30);

        jEmail_textField_.setBackground(new java.awt.Color(108, 122, 137));
        jEmail_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jEmail_textField_.setForeground(new java.awt.Color(228, 241, 254));
        jEmail_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmail_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(jEmail_textField_);
        jEmail_textField_.setBounds(360, 290, 130, 30);

        jDOB_textField_.setBackground(new java.awt.Color(108, 122, 137));
        jDOB_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jDOB_textField_.setForeground(new java.awt.Color(228, 241, 254));
        jDOB_textField_.setToolTipText("");
        jDOB_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDOB_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(jDOB_textField_);
        jDOB_textField_.setBounds(630, 140, 130, 30);

        bloodGroup_textField_.setBackground(new java.awt.Color(108, 122, 137));
        bloodGroup_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        bloodGroup_textField_.setForeground(new java.awt.Color(228, 241, 254));
        bloodGroup_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroup_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(bloodGroup_textField_);
        bloodGroup_textField_.setBounds(630, 180, 130, 30);

        phoneNo_textField_.setBackground(new java.awt.Color(108, 122, 137));
        phoneNo_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        phoneNo_textField_.setForeground(new java.awt.Color(228, 241, 254));
        phoneNo_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNo_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(phoneNo_textField_);
        phoneNo_textField_.setBounds(630, 220, 130, 30);

        fName_textField_.setBackground(new java.awt.Color(108, 122, 137));
        fName_textField_.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        fName_textField_.setForeground(new java.awt.Color(228, 241, 254));
        fName_textField_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fName_textField_ActionPerformed(evt);
            }
        });
        jPanel1.add(fName_textField_);
        fName_textField_.setBounds(360, 130, 130, 30);

        jButton_Clear_.setBackground(new java.awt.Color(242, 38, 19));
        jButton_Clear_.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_Clear_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_Clear_.setText("Clear");
        jButton_Clear_.setToolTipText("Clear");
        jButton_Clear_.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Clear_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Clear_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Clear_);
        jButton_Clear_.setBounds(540, 370, 90, 30);

        jButton_Register_.setBackground(new java.awt.Color(34, 167, 240));
        jButton_Register_.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_Register_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_Register_.setText("Register");
        jButton_Register_.setToolTipText("Register");
        jButton_Register_.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_Register_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Register_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_Register_MouseEntered(evt);
            }
        });
        jButton_Register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Register_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_Register_);
        jButton_Register_.setBounds(670, 370, 90, 30);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setText("(dd-mm-yy)");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(530, 150, 60, 30);

        jBack_Button_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\back1.png")); // NOI18N
        jBack_Button_.setToolTipText("Back");
        jBack_Button_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_Button_MouseClicked(evt);
            }
        });
        jPanel1.add(jBack_Button_);
        jBack_Button_.setBounds(280, 80, 20, 20);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setText("  :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(600, 140, 20, 30);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setText("  :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(330, 370, 20, 30);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("  :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(600, 180, 20, 30);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("Address        :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(530, 260, 90, 30);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setText("Phone No      :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(530, 220, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Group        ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 190, 90, 30);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Blood");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 170, 90, 30);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("DOB          ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 130, 90, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Confirm");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 360, 110, 30);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Password        ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 380, 110, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Password         :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 330, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Email               :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 290, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Username         :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 250, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Middle Name   :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 170, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Last Name        :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 210, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("First Name       :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 130, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMIN REGISTRATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 60, 180, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\reg.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fName_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fName_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fName_textField_ActionPerformed

    private void mName_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mName_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mName_textField_ActionPerformed

    private void lName_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lName_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lName_textField_ActionPerformed

    private void userName_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userName_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userName_textField_ActionPerformed

    private void jEmail_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmail_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmail_textField_ActionPerformed

    private void jDOB_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDOB_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDOB_textField_ActionPerformed

    private void bloodGroup_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroup_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroup_textField_ActionPerformed

    private void phoneNo_textField_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNo_textField_ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNo_textField_ActionPerformed

    private void jBack_Button_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_Button_MouseClicked
            Admin admin = new Admin();
            admin.setVisible(true);
            admin.pack();
            admin.setLocationRelativeTo(null);
            admin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            this.dispose();
    }//GEN-LAST:event_jBack_Button_MouseClicked

    private void jButton_Clear_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Clear_ActionPerformed
        fName_textField_.setText("");
        mName_textField_.setText("");
        lName_textField_.setText("");
        userName_textField_.setText("");
        jEmail_textField_.setText("");
        txt_password1.setText("");
        txt_password.setText("");
        jDOB_textField_.setText("");
        bloodGroup_textField_.setText("");
        phoneNo_textField_.setText("");
        jAddress_textArea_.setText("");
        
    }//GEN-LAST:event_jButton_Clear_ActionPerformed

    private void jButton_Register_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Register_MouseClicked
        
        
    }//GEN-LAST:event_jButton_Register_MouseClicked

    public boolean checkUsername(String username){
    
    PreparedStatement ps;
    ResultSet rs;
    boolean checkUser = false;
    String query = "SELECT * FROM `admin_login` WHERE `Username` = ?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, username);
            rs = ps.executeQuery();
            
            if(rs.next()){
                
                checkUser = true;
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AddAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        return checkUser;
    }
    
    
    private void jButton_Register_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Register_MouseEntered
        
    }//GEN-LAST:event_jButton_Register_MouseEntered

    private void jButton_Register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Register_ActionPerformed
        
        
        String fname = fName_textField_.getText();
        String mname = mName_textField_.getText();
        String lname = lName_textField_.getText();
        String username = userName_textField_.getText();
        String email = jEmail_textField_.getText().toLowerCase();
        String pass = String.valueOf(txt_password1.getPassword());
        String repass = String.valueOf(txt_password.getPassword());
        String dob = jDOB_textField_.getText();
        String blood = bloodGroup_textField_.getText().toUpperCase();
        String phoneno = phoneNo_textField_.getText();
        String address = jAddress_textArea_.getText();
        Pattern p = Pattern.compile("^[7-9][0-9]{9}$");
        Matcher m = p.matcher(phoneno);
        
        if (fname.equals("")) {
        JOptionPane.showMessageDialog(null, "First Name Field is empty","Registration Failed",2);
        } else if (lname.equals("")) {
        JOptionPane.showMessageDialog(null, "Last Name Field is empty","Registration Failed",2);
        }else if (username.equals("")) {
        JOptionPane.showMessageDialog(null, "Username Field is empty","Registration Failed",2);
        }else if (checkUsername(username)) {
        JOptionPane.showMessageDialog(null, "This Username is already taken","Registration Failed",2);
        }else if (email.equals("")) {
        JOptionPane.showMessageDialog(null, "Email Field is empty","Registration Failed",2);
        }else if (pass.equals("")) {
        JOptionPane.showMessageDialog(null, "Password Field is empty","Registration Failed",2);
        }else if (repass.equals("")) {
        JOptionPane.showMessageDialog(null, "Confirm Password Field is empty","Registration Failed",2);
        }else if (!pass.equals(repass)) {
        JOptionPane.showMessageDialog(null, "Password Mismatched","Registration Failed",2);
        }else if (dob.equals("")) {
        JOptionPane.showMessageDialog(null, "DOB Field is empty","Registration Failed",2);
        }else if (blood.equals("")) {
        JOptionPane.showMessageDialog(null, "Blood Group Field is empty","Registration Failed",2);
        }else if (phoneno.equals("")) {
        JOptionPane.showMessageDialog(null, "Phone Number Field is empty","Registration Failed",2);
        }else if (!m.matches()) {
        JOptionPane.showMessageDialog(null, "Invalid Phone Number","Registration Failed",2);
        }else if (address.equals("")) {
        JOptionPane.showMessageDialog(null, "Address Field is empty","Registration Failed",2);
        }else {
            
        PreparedStatement ps;
        
        String query ="INSERT INTO `admin_login`(`First Name`, `Middle Name`, `Last Name`, `Username`, `Email`, `password`, `DOB`, `Blood Group`, `Phone No`, `Address`) VALUES (?,?,?,?,?,?,?,?,?,?)";
        try {
            
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, fname);
            ps.setString(2, mname);
            ps.setString(3, lname);
            ps.setString(4, username);
            ps.setString(5, email);
            ps.setString(6, pass);
            ps.setString(7, dob);
            ps.setString(8, blood);
            ps.setString(9, phoneno);
            ps.setString(10, address);
            
            if(ps.executeUpdate()>0)
            {
            
                JOptionPane.showMessageDialog(null, "New Admin Added","Registration Successfull",JOptionPane.INFORMATION_MESSAGE);
            
            }
            fName_textField_.setText("");
            mName_textField_.setText("");
            lName_textField_.setText("");
            userName_textField_.setText("");
            jEmail_textField_.setText("");
            txt_password1.setText("");
            txt_password.setText("");
            jDOB_textField_.setText("");
            bloodGroup_textField_.setText("");
            phoneNo_textField_.setText("");
            jAddress_textArea_.setText("");
          
         
        } catch (SQLException ex) {
            Logger.getLogger(AddAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton_Register_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodGroup_textField_;
    private javax.swing.JTextField fName_textField_;
    private javax.swing.JTextArea jAddress_textArea_;
    private javax.swing.JLabel jBack_Button_;
    private javax.swing.JButton jButton_Clear_;
    private javax.swing.JButton jButton_Register_;
    private javax.swing.JTextField jDOB_textField_;
    private javax.swing.JTextField jEmail_textField_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lName_textField_;
    private javax.swing.JTextField mName_textField_;
    private javax.swing.JTextField phoneNo_textField_;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_password1;
    private javax.swing.JTextField userName_textField_;
    // End of variables declaration//GEN-END:variables
   
}
