/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package NewEntries;

import Classes.MyConnection;
import Admin.Parents;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aby Balu
 */
public class AddParents extends javax.swing.JFrame {

    /**
     * Creates new form AddParents
     */
    public AddParents() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAddress = new javax.swing.JTextArea();
        middleName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jEmail = new javax.swing.JTextField();
        f_m = new javax.swing.JTextField();
        streamStudent = new javax.swing.JTextField();
        jOccupation = new javax.swing.JTextField();
        jDOB = new javax.swing.JTextField();
        bloodGroup = new javax.swing.JTextField();
        phoneNo = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        jButton_clear_ = new javax.swing.JButton();
        jButton_register_ = new javax.swing.JButton();
        jBack_Button_ = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jAddress.setBackground(new java.awt.Color(108, 122, 137));
        jAddress.setColumns(20);
        jAddress.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jAddress.setForeground(new java.awt.Color(228, 241, 254));
        jAddress.setLineWrap(true);
        jAddress.setRows(5);
        jScrollPane1.setViewportView(jAddress);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(630, 250, 130, 100);

        middleName.setBackground(new java.awt.Color(108, 122, 137));
        middleName.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        middleName.setForeground(new java.awt.Color(228, 241, 254));
        middleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleNameActionPerformed(evt);
            }
        });
        jPanel1.add(middleName);
        middleName.setBounds(360, 170, 130, 30);

        lastName.setBackground(new java.awt.Color(108, 122, 137));
        lastName.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        lastName.setForeground(new java.awt.Color(228, 241, 254));
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });
        jPanel1.add(lastName);
        lastName.setBounds(360, 210, 130, 30);

        jEmail.setBackground(new java.awt.Color(108, 122, 137));
        jEmail.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jEmail.setForeground(new java.awt.Color(228, 241, 254));
        jEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailActionPerformed(evt);
            }
        });
        jPanel1.add(jEmail);
        jEmail.setBounds(360, 250, 130, 30);

        f_m.setBackground(new java.awt.Color(108, 122, 137));
        f_m.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        f_m.setForeground(new java.awt.Color(228, 241, 254));
        f_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f_mActionPerformed(evt);
            }
        });
        jPanel1.add(f_m);
        f_m.setBounds(360, 290, 130, 30);

        streamStudent.setBackground(new java.awt.Color(108, 122, 137));
        streamStudent.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        streamStudent.setForeground(new java.awt.Color(228, 241, 254));
        streamStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streamStudentActionPerformed(evt);
            }
        });
        jPanel1.add(streamStudent);
        streamStudent.setBounds(360, 330, 130, 30);

        jOccupation.setBackground(new java.awt.Color(108, 122, 137));
        jOccupation.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jOccupation.setForeground(new java.awt.Color(228, 241, 254));
        jOccupation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOccupationActionPerformed(evt);
            }
        });
        jPanel1.add(jOccupation);
        jOccupation.setBounds(360, 370, 130, 30);

        jDOB.setBackground(new java.awt.Color(108, 122, 137));
        jDOB.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jDOB.setForeground(new java.awt.Color(228, 241, 254));
        jDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDOBActionPerformed(evt);
            }
        });
        jPanel1.add(jDOB);
        jDOB.setBounds(630, 130, 130, 30);

        bloodGroup.setBackground(new java.awt.Color(108, 122, 137));
        bloodGroup.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        bloodGroup.setForeground(new java.awt.Color(228, 241, 254));
        bloodGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupActionPerformed(evt);
            }
        });
        jPanel1.add(bloodGroup);
        bloodGroup.setBounds(630, 170, 130, 30);

        phoneNo.setBackground(new java.awt.Color(108, 122, 137));
        phoneNo.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        phoneNo.setForeground(new java.awt.Color(228, 241, 254));
        phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoActionPerformed(evt);
            }
        });
        jPanel1.add(phoneNo);
        phoneNo.setBounds(630, 210, 130, 30);

        firstName.setBackground(new java.awt.Color(108, 122, 137));
        firstName.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        firstName.setForeground(new java.awt.Color(228, 241, 254));
        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });
        jPanel1.add(firstName);
        firstName.setBounds(360, 130, 130, 30);

        jButton_clear_.setBackground(new java.awt.Color(242, 38, 19));
        jButton_clear_.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_clear_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_clear_.setText("Clear");
        jButton_clear_.setToolTipText("Clear");
        jButton_clear_.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_clear_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clear_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_clear_);
        jButton_clear_.setBounds(540, 370, 90, 30);

        jButton_register_.setBackground(new java.awt.Color(34, 167, 240));
        jButton_register_.setFont(new java.awt.Font("Montserrat", 1, 12)); // NOI18N
        jButton_register_.setForeground(new java.awt.Color(236, 240, 241));
        jButton_register_.setText("Register");
        jButton_register_.setToolTipText("Register");
        jButton_register_.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_register_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_register_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_register_MouseEntered(evt);
            }
        });
        jButton_register_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_register_ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton_register_);
        jButton_register_.setBounds(670, 370, 90, 30);

        jBack_Button_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\back1.png")); // NOI18N
        jBack_Button_.setToolTipText("Back");
        jBack_Button_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBack_Button_MouseClicked(evt);
            }
        });
        jPanel1.add(jBack_Button_);
        jBack_Button_.setBounds(280, 80, 20, 20);

        jLabel18.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(236, 240, 241));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("  :");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(330, 330, 20, 30);

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(236, 240, 241));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("  :");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(600, 170, 20, 30);

        jLabel17.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(236, 240, 241));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("  :");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(330, 290, 20, 30);

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(236, 240, 241));
        jLabel16.setText("Occupation        :");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(250, 370, 110, 30);

        jLabel15.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(236, 240, 241));
        jLabel15.setText("Address          :");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(530, 250, 90, 30);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(236, 240, 241));
        jLabel14.setText("Phone No        :");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(530, 210, 90, 30);

        jLabel13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(236, 240, 241));
        jLabel13.setText("Group        ");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(530, 180, 80, 30);

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(236, 240, 241));
        jLabel12.setText("Blood");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(530, 160, 80, 30);

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(236, 240, 241));
        jLabel10.setText("Father/");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(250, 280, 100, 30);

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(236, 240, 241));
        jLabel9.setText("Mother of       ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(250, 300, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(236, 240, 241));
        jLabel8.setText("Stream of");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(250, 320, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(236, 240, 241));
        jLabel7.setText("Student          ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(250, 340, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Email                :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(250, 250, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(236, 240, 241));
        jLabel5.setText("Middle Name    :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(250, 170, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(236, 240, 241));
        jLabel4.setText("Last Name         :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(250, 210, 100, 30);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(236, 240, 241));
        jLabel3.setText("First Name        :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 130, 100, 30);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(236, 240, 241));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PARENT REGISTRATION");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(400, 60, 220, 60);

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(236, 240, 241));
        jLabel20.setText("(dd-mm-yy)");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(530, 140, 60, 30);

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(236, 240, 241));
        jLabel11.setText("DOB          ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(530, 120, 90, 30);

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(236, 240, 241));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("  :");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(600, 130, 20, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\reg.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1021, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void middleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleNameActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void jEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailActionPerformed

    private void f_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f_mActionPerformed

    private void streamStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streamStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streamStudentActionPerformed

    private void jOccupationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOccupationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jOccupationActionPerformed

    private void jDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDOBActionPerformed

    private void bloodGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupActionPerformed

    private void phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNoActionPerformed

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void jBack_Button_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBack_Button_MouseClicked
        Parents parents = new Parents();
        parents.setVisible(true);
        parents.pack();
        parents.setLocationRelativeTo(null);
        parents.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jBack_Button_MouseClicked
    
    private void jButton_clear_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clear_ActionPerformed
        firstName.setText("");
        middleName.setText("");
        lastName.setText("");
        jEmail.setText("");
        f_m.setText("");
        streamStudent.setText("");
        jOccupation.setText("");
        jDOB.setText("");
        bloodGroup.setText("");
        phoneNo.setText("");
        jAddress.setText("");
    }//GEN-LAST:event_jButton_clear_ActionPerformed

    private void jButton_register_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_register_MouseClicked
        
        String fname = firstName.getText();
        String mname = middleName.getText();
        String lname = lastName.getText();
        String email = jEmail.getText().toLowerCase();
        String fm = f_m.getText();
        String ststud = streamStudent.getText();
        String occupation = jOccupation.getText();
        String dob = jDOB.getText();
        String blood = bloodGroup.getText().toUpperCase();
        String phoneno = phoneNo.getText();
        String address = jAddress.getText();
        Pattern p = Pattern.compile("^[7-9][0-9]{9}$");
        Matcher m = p.matcher(phoneno);
        
        if (fname.equals("")) {
        JOptionPane.showMessageDialog(null, "First Name Field is empty","Registration Failed",2);
        } else if (lname.equals("")) {
        JOptionPane.showMessageDialog(null, "Last Name Field is empty","Registration Failed",2);
        }else if (email.equals("")) {
        JOptionPane.showMessageDialog(null, "Email Field is empty","Registration Failed",2);
        }else if (fm.equals("")) {
        JOptionPane.showMessageDialog(null, "Father / Mother of Field is empty","Registration Failed",2);
        }else if (ststud.equals("")) {
        JOptionPane.showMessageDialog(null, "Stream of Student Field is empty","Registration Failed",2);
        }else if (occupation.equals("")) {
        JOptionPane.showMessageDialog(null, "Occupation Field is empty","Registration Failed",2);
        }else if (dob.equals("")) {
        JOptionPane.showMessageDialog(null, "DOB Field is empty","Registration Failed",2);
        }else if (blood.equals("")) {
        JOptionPane.showMessageDialog(null, "Blood Group Field is empty","Registration Failed",2);
        }else if (phoneno.equals("")) {
        JOptionPane.showMessageDialog(null, "Phone Number Field is empty","Registration Failed",2);
        }else if (!m.matches()) {
        JOptionPane.showMessageDialog(null, "Invalid Phone Number","Registration Failed",2);
        }else if (address.equals("")) {
        JOptionPane.showMessageDialog(null, "Address Field is empty","Registration Failed",2);
        }else {
            
        PreparedStatement ps;
        
        String query ="INSERT INTO `parent_details`(`First Name`, `Middle Name`, `Last Name`, `Email`, `F/M of`,`Stream of Student`, `Occupation`, `DOB`, `Blood Group`, `Phone No`, `Address`) VALUES (?,?,?,?,?,?,?,?,?,?,?)";
        try {
            
            ps = MyConnection.getConnection().prepareStatement(query);
            ps.setString(1, fname);
            ps.setString(2, mname);
            ps.setString(3, lname);
            ps.setString(4, email);
            ps.setString(5, fm);
            ps.setString(6, ststud);
            ps.setString(7, occupation);
            ps.setString(8, dob);
            ps.setString(9, blood);
            ps.setString(10, phoneno);
            ps.setString(11, address);
            
            if(ps.executeUpdate()>0)
            {
            
                JOptionPane.showMessageDialog(null, "New Parent details added","Registration Successfull",JOptionPane.INFORMATION_MESSAGE);
            
            }
            firstName.setText("");
            middleName.setText("");
            lastName.setText("");
            jEmail.setText("");
            f_m.setText("");
            streamStudent.setText("");
            jOccupation.setText("");
            jDOB.setText("");
            bloodGroup.setText("");
            phoneNo.setText("");
            jAddress.setText("");
          
         
        } catch (SQLException ex) {
            Logger.getLogger(AddParents.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_jButton_register_MouseClicked

    private void jButton_register_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_register_MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_register_MouseEntered

    private void jButton_register_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_register_ActionPerformed

    }//GEN-LAST:event_jButton_register_ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddParents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddParents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddParents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddParents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddParents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodGroup;
    private javax.swing.JTextField f_m;
    private javax.swing.JTextField firstName;
    private javax.swing.JTextArea jAddress;
    private javax.swing.JLabel jBack_Button_;
    private javax.swing.JButton jButton_clear_;
    private javax.swing.JButton jButton_register_;
    private javax.swing.JTextField jDOB;
    private javax.swing.JTextField jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jOccupation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField middleName;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JTextField streamStudent;
    // End of variables declaration//GEN-END:variables
}
