/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Student;

import Guest.Glogin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Aby Balu
 */
public class Shome extends javax.swing.JFrame {

    /** Creates new form Shome */
    public Shome() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton_admin_ = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton_TimeTable_ = new javax.swing.JLabel();
        jButton_Parents_ = new javax.swing.JLabel();
        jButton_Students_ = new javax.swing.JLabel();
        jButton_Teachers_ = new javax.swing.JLabel();
        jButton_Home_ = new javax.swing.JLabel();
        jButton_Logout_ = new javax.swing.JLabel();
        jButton_TimeTable2_ = new javax.swing.JLabel();
        jButton_Parents2_ = new javax.swing.JLabel();
        jButton_Students2_ = new javax.swing.JLabel();
        jButton_Teachers2_ = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\in.png")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 80, 20, 20);

        jButton_admin_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\admin.png")); // NOI18N
        jButton_admin_.setToolTipText("Admin Manager");
        jButton_admin_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_admin_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_admin_);
        jButton_admin_.setBounds(20, 10, 100, 40);

        jLabel14.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ADMIN");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(20, 10, 130, 40);

        jButton_TimeTable_.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton_TimeTable_.setForeground(new java.awt.Color(204, 204, 204));
        jButton_TimeTable_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_TimeTable_.setText("  Timetable");
        jButton_TimeTable_.setToolTipText("Timetable Manager");
        jButton_TimeTable_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_TimeTable_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_TimeTable_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_TimeTable_);
        jButton_TimeTable_.setBounds(-10, 230, 150, 40);

        jButton_Parents_.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton_Parents_.setForeground(new java.awt.Color(204, 204, 204));
        jButton_Parents_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Parents_.setText("Parents");
        jButton_Parents_.setToolTipText("Parent Manager");
        jButton_Parents_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Parents_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Parents_);
        jButton_Parents_.setBounds(10, 190, 120, 40);

        jButton_Students_.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton_Students_.setForeground(new java.awt.Color(204, 204, 204));
        jButton_Students_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Students_.setText("  Students");
        jButton_Students_.setToolTipText("Student Manager");
        jButton_Students_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Students_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Students_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Students_);
        jButton_Students_.setBounds(-10, 150, 150, 40);

        jButton_Teachers_.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton_Teachers_.setForeground(new java.awt.Color(204, 204, 204));
        jButton_Teachers_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Teachers_.setText(" Teachers");
        jButton_Teachers_.setToolTipText("Teacher Manager");
        jButton_Teachers_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Teachers_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Teachers_);
        jButton_Teachers_.setBounds(10, 110, 120, 40);

        jButton_Home_.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jButton_Home_.setForeground(new java.awt.Color(204, 204, 204));
        jButton_Home_.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jButton_Home_.setText("   Home");
        jButton_Home_.setToolTipText("Home");
        jButton_Home_.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton_Home_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Home_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Home_);
        jButton_Home_.setBounds(-10, 70, 150, 40);

        jButton_Logout_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\logout.png")); // NOI18N
        jButton_Logout_.setToolTipText("Logout");
        jButton_Logout_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Logout_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Logout_);
        jButton_Logout_.setBounds(970, 10, 30, 40);

        jButton_TimeTable2_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\timetable1.png")); // NOI18N
        jButton_TimeTable2_.setToolTipText("Timetable Manager");
        jButton_TimeTable2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_TimeTable2_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_TimeTable2_);
        jButton_TimeTable2_.setBounds(800, 80, 150, 80);

        jButton_Parents2_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\parents1.png")); // NOI18N
        jButton_Parents2_.setToolTipText("Parent Manager");
        jButton_Parents2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Parents2_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Parents2_);
        jButton_Parents2_.setBounds(610, 80, 150, 80);

        jButton_Students2_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\student1.png")); // NOI18N
        jButton_Students2_.setToolTipText("Student Manager");
        jButton_Students2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Students2_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Students2_);
        jButton_Students2_.setBounds(420, 80, 150, 80);

        jButton_Teachers2_.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\teacher1.png")); // NOI18N
        jButton_Teachers2_.setToolTipText("Teacher Manager");
        jButton_Teachers2_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_Teachers2_MouseClicked(evt);
            }
        });
        jPanel1.add(jButton_Teachers2_);
        jButton_Teachers2_.setBounds(220, 80, 150, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\Timetable_Management_System\\src\\main\\java\\Resources\\home.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1020, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_admin_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_admin_MouseClicked
        JOptionPane.showMessageDialog(null, "Acces Restricted","Request Denied",2);
    }//GEN-LAST:event_jButton_admin_MouseClicked

    private void jButton_TimeTable_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_TimeTable_MouseClicked
        Stimetable timetable = new Stimetable();
        timetable.setVisible(true);
        timetable.pack();
        timetable.setLocationRelativeTo(null);
        timetable.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_TimeTable_MouseClicked

    private void jButton_Parents_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Parents_MouseClicked
        JOptionPane.showMessageDialog(null, "Acces Restricted","Request Denied",2);
    }//GEN-LAST:event_jButton_Parents_MouseClicked

    private void jButton_Students_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Students_MouseClicked
        JOptionPane.showMessageDialog(null, "Acces Restricted","Request Denied",2);
    }//GEN-LAST:event_jButton_Students_MouseClicked

    private void jButton_Teachers_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Teachers_MouseClicked
        Steachers teacher = new Steachers();
        teacher.setVisible(true);
        teacher.pack();
        teacher.setLocationRelativeTo(null);
        teacher.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Teachers_MouseClicked

    private void jButton_Home_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Home_MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_Home_MouseClicked

    private void jButton_Logout_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Logout_MouseClicked
        Glogin out = new Glogin();
        out.setVisible(true);
        out.pack();
        out.setLocationRelativeTo(null);
        out.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Logout_MouseClicked

    private void jButton_TimeTable2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_TimeTable2_MouseClicked
        Stimetable timetable = new Stimetable();
        timetable.setVisible(true);
        timetable.pack();
        timetable.setLocationRelativeTo(null);
        timetable.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_TimeTable2_MouseClicked

    private void jButton_Parents2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Parents2_MouseClicked
        JOptionPane.showMessageDialog(null, "Acces Restricted","Request Denied",2);
    }//GEN-LAST:event_jButton_Parents2_MouseClicked

    private void jButton_Students2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Students2_MouseClicked
        JOptionPane.showMessageDialog(null, "Acces Restricted","Request Denied",2);
    }//GEN-LAST:event_jButton_Students2_MouseClicked

    private void jButton_Teachers2_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_Teachers2_MouseClicked
        Steachers teacher = new Steachers();
        teacher.setVisible(true);
        teacher.pack();
        teacher.setLocationRelativeTo(null);
        teacher.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton_Teachers2_MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Shome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Shome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Shome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Shome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Shome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jButton_Home_;
    private javax.swing.JLabel jButton_Logout_;
    private javax.swing.JLabel jButton_Parents2_;
    private javax.swing.JLabel jButton_Parents_;
    private javax.swing.JLabel jButton_Students2_;
    private javax.swing.JLabel jButton_Students_;
    private javax.swing.JLabel jButton_Teachers2_;
    private javax.swing.JLabel jButton_Teachers_;
    private javax.swing.JLabel jButton_TimeTable2_;
    private javax.swing.JLabel jButton_TimeTable_;
    private javax.swing.JLabel jButton_admin_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
